# ======================================================================== #
#  alacritty - alacritty.toml                                              #
#  Maintainer: sungyoonc                                                   #
# ======================================================================== #
#                                                                          #
#                                                                          #
#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗  #
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝  #
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝   #
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝    #
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║     #
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝     #
#                                                                          #
#                                                                          #
# ======================================================================== #

# Theme
import = ["/home/fox/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[font]
size = 11

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

# Keys
[keyboard]
bindings = [
    # Control Sequence Introducer + Unicode Decimal + Modifier + u (Stands for unicode)
    # \u001b[                       59              ; 5          u
    # Modifier: 1=None, (1=Shift, 2=Alt, 4=Ctrl)+1
    { key= "Semicolon", mods= "Control", chars= "\u001b[59;4u" },
]
