# ======================================================================== #
#  alacritty - alacritty.toml                                              #
#  Maintainer: sungyoonc                                                   #
# ======================================================================== #
#                                                                          #
#                                                                          #
#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗  #
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝  #
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝   #
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝    #
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║     #
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝     #
#                                                                          #
#                                                                          #
# ======================================================================== #

# Theme
import = ["/home/fox/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[font]
size = 11

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"
