#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    selected=$(find "$1" -maxdepth 0 -type d 2>/dev/null | sed -n '1p')
else
    fzf_list=$(
        find ~/personal -mindepth 0 -maxdepth 1 -type d
        # `-name ".*" -prune`: matches file/dir that didn't start with a dot
        # `-o -print`: print if the previous expression did not match
        find ~/syncthing/Notes -mindepth 1 -maxdepth 1 -type d -name ".*" -prune -o -print
        find ~/school -mindepth 1 -maxdepth 2 -type d -path '*/[0-9]-[0-9]*'
        find ~/.dotfiles ~/school -maxdepth 0 -type d
    )
    selected=$(echo "$fzf_list" | fzf --cycle --bind 'change:first,tab:up,btab:down')
fi

if [ -z $selected ]; then
    exit 0
fi

if [ $# -eq 2 ]; then
    selected_name="$(echo $2 | tr .: _)"
else
    selected_name=$(basename "$(realpath -s "$selected")" | tr ".:" "__")
fi
tmux_running=$(pgrep tmux)

if [ -z "$TMUX" ] && [ -z "$tmux_running" ]; then
    tmux new-session -s "$selected_name" -c $selected
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c $selected
fi

if [ -z "$TMUX" ]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
