#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    selected=$(find "$1" -maxdepth 0 -type d 2>/dev/null | sed -n '1p')
else
    # tmux_list=$(tmux list-session -F '#{session_path}' 2>/dev/null | sort | uniq -u)

    # Add directory specific dirs to find_list
    if [ -f "./.tms" ]; then
        find_list=$(
            jq -r '.list.dirs[]' ".tms" 2>/dev/null | xargs -I _ find _ -maxdepth 0 -type d 2>/dev/null
        )
        if [ -n "$find_list" ]; then
            find_list+=$'\n'
        fi
    fi
    find_list+=$(
        find ~/personal -mindepth 0 -maxdepth 1 -type d
        find ~/syncthing/Notes -mindepth 1 -maxdepth 1 -type d -name ".*" -prune -o -print
        find ~/school -mindepth 1 -maxdepth 2 -type d -path '*/[0-9]-[0-9]*'
        find ~/.dotfiles ~/school -maxdepth 0 -type d
    )
    selected=$(echo "$find_list" | fzf --scheme=path --cycle --bind 'change:first,tab:up,btab:down')
fi

if [ -z "$selected" ]; then
    exit 1
fi

# Expand the selected path
selected="$(realpath -s "$selected")"

# Get the name for the session
if [ $# -eq 2 ]; then
    selected_name="$(echo $2 | tr .: _)"
else
    selected_name=$(basename "$selected" | tr ".:" "__")
fi

tmux_running=$(pgrep tmux)

if [ -z "$TMUX" ] && [ -z "$tmux_running" ]; then
    tmux new-session -s "$selected_name" -c $selected
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c $selected
fi

if [ -z "$TMUX" ]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
