#!/usr/bin/env bash

stow() {
    $(which stow) "$@" 2> >(grep -v 'BUG in find_stowed_path? Absolute/relative mismatch' 1>&2)
}

stow -D --no-folding --target=$HOME */

pushd .images > /dev/null
stow -D --no-folding --target=$HOME */
popd > /dev/null
