#!/usr/bin/env bash

is_enabled() {
    # Make temp state for device
    status=$(cat "${temp_file}")
    if [ "$status" == "false" ]; then # Device is disabled
        return 1
    else # Assume device is enabled
        return 0
    fi
    >&2 echo "Failed to get device status"
    exit 1
}

enable_device() {
    notify-send -u normal --category="device" "${text_icon_enable} Enabled ${display_name}"
    printf true >"$temp_file"
    hyprctl keyword "\$${device_var_name}" "true" -r
}

disable_device() {
    notify-send -u normal --category="device" "${text_icon_disable} Disaled ${display_name}"
    printf false >"$temp_file"
    hyprctl keyword "\$${device_var_name}" "false" -r
}

device_var_name="${1? "Usage: $0 <device_var_name> <display_name> [<text_icon_enable>] [<text_icon_disable>]"}"
display_name="${2? "Usage: $0 <device_var_name> <display_name> [<text_icon_enable>] [<text_icon_disable>]"}"
text_icon_enable="${3:-""}"
text_icon_disable="${4:-""}"

temp_file="/tmp/toggle_device_$device_var_name"
if [ ! -f "$temp_file" ]; then
    printf true >"$temp_file"
fi

# Toggle state
if is_enabled; then
    disable_device
else
    enable_device
fi
